export const diagnosis = [
  "AAPCS",
  "AAIXN",
  "AAOM",
  "ABDP",
  "ABSCESS RIGHT LEG",
  "ABDOMINAL PAIN",
  "ABSCESSES",
  "ABSCESS",
  "AB NEGATIVE",
  "ABPA",
  "ABDCLC",
  "ABNORMAL CBC",
  "ABDCS",
  "ABRASION",
  "ABSCESS LEFT LEG",
  "ABRASSION",
  "ACS",
  "ACUTE EXACERBATION",
  "ACLD",
  "ACD",
  "ACUTE RIGHT LITTLE'S AREA BLEEDING",
  "ACUTE LEFT PREAURICULAR SINUS INFECTION",
  "ACUTE LEFT EAR TRAUMATIC PERFORATION",
  "ACUTE OCCLUSION OF LEFT ARM ARTERY",
  "ACBRCT",
  "ACUTE VIRAL INFECTION",
  "ACTLS",
  "ACLL",
  "ACUTE RIGHT NM NECKPAIN",
  "ACP",
  "ACUTE PHARYNGO BRONCHITIS",
  "ACUTE LEFT TRAUMATIC LARGE PERFORATION",
  "ACUTE RIGHT MIDDLE EAR BLOCKAGE",
  "ACCD",
  "ACUTE VIRAL SYNDROME",
  "ACUTE MILD ALLERGIC ETC LEFT",
  "ACUTE RHINO SINO PHARYNGITIS",
  "AC",
  "ACUTE CONFUSIONAL STATE",
  "ACUTE RHINOSINUSITIS",
  "ACIDITY",
  "ACLT",
  "ACTS",
  "ACCTS",
  "ACDS",
  "ACSTS",
  "ACNEIFORM ERUPTION",
  "ACM",
  "ACUTE CORYZA",
  "ACUTE NASOPHARYNGITIS",
  "ACUTE TRAUMATIC LEFTT NM NECK PAIN",
  "ACHES",
  "ACOS",
  "ACUTE PARONYCHIA",
  "ACID PEPTIC DISEASE",
  "ACNE VGS",
  "ACNGS",
  "ACMGY",
  "ACUTE LEFT  LITTLE'S AREA BLEEDING",
  "ACUTE LEFT SUBMANDIBULAR NM PAIN",
  "ACUTE LEFT EAR TRAUMATIC CANAL INJURY",
  "ACNE",
  "ADRMTS",
  "AD",
  "ADENOID FACIES",
  "ADENOCARCINOMA",
  "ADMYS",
  "ADENOID HYPERTROPHY",
  "ADPKD",
  "ADEQUATE LEFT VENTRICULAR FUNCTION",
  "ADDD",
  "ADCTS",
  "ADHD",
  "ADENOIDITIS",
  "ADRENAL INSUFFICIENCY",
  "AEAMA",
  "AECOPD",
  "AETS",
  "AECB",
  "AENTC",
  "AFI",
  "AFL",
  "AFTN",
  "AGITATION",
  "AGA",
  "AGATCS",
  "AGSETS",
  "AHEPS",
  "AIE",
  "AITD",
  "AION",
  "AIHA",
  "AKD",
  "AKI",
  "ALBRCT",
  "ALCOHOL DEPENDENCE",
  "ALRCTS",
  "ALNV",
  "ALCOHOLISM",
  "ALLERGIC REACTION",
  "ALLERGIC DIATHESIS",
  "ALCOHOL ADDICTION",
  "ALD",
  "ALATA",
  "ALUA",
  "ALFLA",
  "ALURTI",
  "ALLERGY",
  "ALLR",
  "ALGY",
  "ALLERGIC",
  "ALOPECIA",
  "ALCOHOL WITHDRAWAL",
  "ALLERGIC RASHES",
  "ALZHEIMER'S DISEASE",
  "ALFT",
  "ALUS",
  "ALBA",
  "ALYS",
  "ALP",
  "ALCOHOLIC NEUROPATHY",
  "ALPATLS",
  "AMOEBIASIS",
  "AMENORRHEA",
  "AML",
  "AMI",
  "AMENORRHOEA",
  "ANEMIA",
  "ANASARCA",
  "ANLGTS",
  "ANMA",
  "ANGINA",
  "ANOVULATION",
  "ANSP",
  "ANAL FISSURE",
  "ANTERIOR UVEITIS",
  "ANA POSITIVE",
  "ANA",
  "ANA NEGATIVE",
  "ANOREXIA",
  "ANV",
  "ANKLE SPRAIN",
  "ANXIETY",
  "AOCD",
  "AOE",
  "AORTOARTERITIS",
  "AOM",
  "APCRT",
  "APD",
  "APLA",
  "APCS",
  "APH",
  "APYTS",
  "APHASIA",
  "APPETITE",
  "ARCJTS",
  "ARBCTS",
  "ARDS",
  "ARM PAIN",
  "ARFT",
  "ARSTS",
  "ARS",
  "ARF",
  "ARI",
  "ARTS",
  "ARECG",
  "ARNV",
  "ARN",
  "ARST",
  "ARTM",
  "ASC",
  "ASYMPTOMATIC HEART DISEASE",
  "ASTMT",
  "ASTH",
  "ASD",
  "ASOM",
  "ASTHENIA",
  "ASTIGMATISM",
  "ASBHTS",
  "ASCVD",
  "ASYMPTOMATIC",
  "ASMI",
  "ASTEATOTIC ECZEMA",
  "ASH",
  "ASYMPTOMATIC BACTERIURIA",
  "ASTHMA",
  "ATAXIA",
  "ATYPICAL PAIN",
  "ATF INJURY",
  "ATROPHIC SCAR",
  "ATHRMTS",
  "ATOPY",
  "ATGLA",
  "ATHEROTHROMBOTIC",
  "ATF",
  "ATCED",
  "AUDH",
  "AUDRMTS",
  "AURTI",
  "AUTISM",
  "AUB",
  "AVR",
  "AVSCS",
  "AVH",
  "AVM",
  "AVF",
  "AWSTEMI",
  "AWS",
  "AWMI",
  "AXTYNS",
  "AXTY",
  "AZTMA",
  "AZMA",
  "AZOTAEMIA",
  "BALANOPOSTHITIS",
  "BA",
  "BALANITIS",
  "BAV",
  "BACKACHE",
  "BCTS",
  "BDAC",
  "BDTY",
  "BDR",
  "BDPN",
  "BENIGN TENSION TREMORS",
  "BFB",
  "BFS",
  "BGSETS",
  "BHP",
  "BH",
  "BIPOLAR DISORDER",
  "BILATERAL CONTRACTED KIDNEYS",
  "BITTER TASTE",
  "BKSPN",
  "BKP",
  "BLOO",
  "BLOATING",
  "BLBP",
  "BLATMA",
  "BLEEDING",
  "BLACK SKIN",
  "BLUR",
  "BLEEDING PILES",
  "BLKS",
  "BLCR",
  "BLDS",
  "BLPRT",
  "BLTTA",
  "BMV",
  "BONE PAIN",
  "BOILS",
  "BODYACHE",
  "BP",
  "BPY",
  "BPAD",
  "BPD",
  "BPSPKA",
  "BPADS",
  "BPPV",
  "BPV",
  "BPH(BENIGN PROSTATIC HYPERPLASIA)",
  "BPLRD",
  "BPH",
  "BREATHLESSNESS UNDER EVALUATION",
  "BREAST LUMP",
  "BRGDS",
  "BREATHLESSNESS",
  "BRCTS",
  "BRDFT",
  "BRITTLE DIABETES",
  "BRUCELLOSIS",
  "BRONCHOSPASM",
  "BRLNS",
  "BRADYCARDIA",
  "BRLNGA",
  "BRONCHIECTASIS",
  "BSPD",
  "BTTMA",
  "BURN",
  "BURNING MICTURITION",
  "BURNING",
  "BURMTN",
  "BURSITIS",
  "BVHF",
  "BVF",
  "CABG",
  "CALCANEAL SPUR",
  "CAD",
  "CARDIOMYOPATHY",
  "CAPTE",
  "CAE",
  "CAF",
  "CARDIOMEGALY",
  "CATGE",
  "CAHD",
  "CADTS",
  "CAG",
  "CADGS",
  "CAH",
  "CASTH",
  "CA",
  "CAOM",
  "CAVD",
  "CACLN",
  "CATRTS",
  "CAS",
  "CABT",
  "CARBUNCLE",
  "CALF PAIN",
  "CANDIDIASIS",
  "CAOVY",
  "CBA",
  "CBRAXA",
  "CBVLRIY",
  "CBHL",
  "CBATPY",
  "CBLIT",
  "CBKP",
  "CCF",
  "CCYTS",
  "CCTS",
  "CCP",
  "CDF",
  "CDGP",
  "CDR",
  "CEC",
  "CED",
  "CEPHALGIA",
  "CFS",
  "CGN",
  "CGDP",
  "CGHD",
  "CHRONIC COUGH",
  "CHM",
  "CHIKUNGUNYA",
  "CHTS",
  "CHAHYT",
  "CHALAZION",
  "CHADTS",
  "CHRONIC GIDDINESS",
  "CHLTSMNS",
  "CHB",
  "CHD",
  "CHVNS",
  "CHIKV",
  "CHHYMA",
  "CHF",
  "CHRONIC SNORING",
  "CHRONIC BILATERAL PAROTID SIALOSIS",
  "CHA",
  "CHRONIC ECZEMA",
  "CHLOS",
  "CHBRCT",
  "CHICKUNGUNYA FEVER",
  "CHDCFT",
  "CHRONIC ALLERGIC ETC",
  "CHVCPS",
  "CHIFN",
  "CHAKKAR",
  "CHEST HEAVINESS",
  "CHEST PAIN",
  "CHALHM",
  "CHILLS",
  "CHGHYS",
  "CHRONIC MOUTH BREATHING",
  "CHLTGE",
  "CHRSFLR",
  "CHBA",
  "CHRONIC SMOKER",
  "CH",
  "CHRONIC RIGHT TSG",
  "CHARCOT FOOT",
  "CHRONIC ETHANOL INGESTION",
  "CICATRICIAL ALOPECIA",
  "CIDP",
  "CITP",
  "CIC",
  "CIU",
  "CKD STAGE 2",
  "CKP",
  "CKD STAGE 5",
  "CKD STAGE 3",
  "CKD STAGE 3B",
  "CKD STAGE 1",
  "CKD STAGE 3A",
  "CKD",
  "CKD STAGE 4",
  "CKD STAGE 5D",
  "CLBA",
  "CLOMTS",
  "CLIMA",
  "CLD",
  "CLMSPM",
  "CLDABS",
  "CLT",
  "CLLPTY",
  "CLMPY",
  "CLTS",
  "CLCD",
  "CLCHTS",
  "CLAUSTROPHOBIA",
  "CLBP",
  "CLW",
  "CLL",
  "CLYDTS",
  "CLHL",
  "CMA",
  "CMLK",
  "CML",
  "CMPD",
  "CMNM",
  "CMP",
  "CNJTS",
  "CNV",
  "CNIN",
  "CNDIG",
  "CNVD",
  "COUGH UNDER EVALUATION",
  "COPD",
  "COAD",
  "COLITIS",
  "COMPLICATED PREGNANCY",
  "COUGH",
  "COLIC",
  "COLONIC INFECTION",
  "CORN",
  "CONTUSION",
  "CONVULSION",
  "COSMETIC DAMAGED FACE",
  "COE",
  "CORYZA",
  "CORNEAL ULCER",
  "CONSTIPATION",
  "COLLOID MILIUM",
  "COCCYDYNIA",
  "COLD",
  "CPE",
  "CPS",
  "CP",
  "CPPD",
  "CPSZ",
  "CPYTS",
  "CPDMA",
  "CRVO",
  "CRESK",
  "CRDAT",
  "CRDTY",
  "CRS",
  "CRF",
  "CRHD",
  "CRP",
  "CRARTS",
  "CRLPYA",
  "CRACK",
  "CRISIS",
  "CRD",
  "CRCDS",
  "CRVCA",
  "CRAMPS",
  "CSA",
  "CSOM",
  "CSYM",
  "CSYTS",
  "CSME",
  "CTH",
  "CTE",
  "CTRCT",
  "CTS",
  "CTRLPP",
  "CTCHD",
  "CTLDA",
  "CTPN",
  "CTTH",
  "CUA",
  "CUH",
  "CUTANEOUS HORN",
  "CVT",
  "CVNDSR",
  "CVASTH",
  "CVA",
  "CVD",
  "CVE",
  "CVLSTN",
  "CVS",
  "CVM",
  "CVLSPN",
  "CVLPN",
  "CVST",
  "CYSTITIS",
  "CYST",
  "DANDRUFF",
  "DARA",
  "DARK COLOR URINE",
  "DCLD",
  "DCLC",
  "DCM",
  "DDPTY",
  "DEAFNESS",
  "DEXTROCARDIA",
  "DEHYDRATION",
  "DENGUE",
  "DEPIGMENTATION",
  "DELAYED MENSES",
  "DENGUE FEVER",
  "DEPYS",
  "DEMENTIA",
  "DELAYED PUBERTY",
  "DEBILITY",
  "DELAYED SPEECH",
  "DENTAL INFECTION",
  "DENTAL CARIES",
  "DEPRESSION",
  "DFS",
  "DFU",
  "DGEPTY",
  "DGSND",
  "DHF",
  "DIABETIC SHIN SPOTS",
  "DIABETIC ARTHOPATHY",
  "DISTENSION",
  "DIABETIC FOOT",
  "DIPLOPIA",
  "DIABETIC DIET",
  "DISORDER",
  "DIET PLAN",
  "DIABETIC BULLAE REPTURE",
  "DIARRHOEA",
  "DIZZINESS",
  "DIET",
  "DISC PROLAPSE",
  "DKD",
  "DKA",
  "DKD STAGE 3",
  "DLBCL",
  "DLFT",
  "DLC",
  "DLE",
  "DNS",
  "DNTS",
  "DNEPTY",
  "DN",
  "DNLAS",
  "DOE",
  "DOG BITE",
  "DPPN",
  "DPN",
  "DPSN",
  "DPSDR",
  "DRY HEALING PERFORATION",
  "DRPY",
  "DRUG ALLERGY",
  "DRY LARGE PERFORATION",
  "DRUG INDUCED",
  "DRUG INDUCED PURPURIC RASH",
  "DRY SKIN",
  "DRUG INDUCED GALACTORRHOEA",
  "DRYNESS OF MOUTH",
  "DRMTS",
  "DRY EYES",
  "DRUG REACTION",
  "DRY MOUTH",
  "DRMYTS",
  "DSVD",
  "DSMN",
  "DSPN",
  "DTPTY",
  "DTBDSLP",
  "DTLDYS",
  "DTG",
  "DULL EYES",
  "DULL RIGHT EYE",
  "DULL LEFT EYE",
  "DUB",
  "DULCR",
  "DVR",
  "DVT",
  "DVCAD",
  "DWNS",
  "DYSURIA",
  "DYMSYM",
  "DYSPNOEA",
  "DYSMENORRHEA",
  "DYSPHAGIA",
  "DYSL",
  "DYSBIOSIS",
  "DYSP",
  "DYSENTRY",
  "DYSELECTROLYTEMIA",
  "DYSPEPSIA",
  "DYPMA",
  "EARLY PREGNANCY",
  "EARLY MENOPAUSE",
  "EAR WAX",
  "EARLY PUBERTY",
  "ECZEMA",
  "ECS",
  "ECTOPIC THYROID",
  "EDEMA",
  "ED",
  "EFFORT ANGINA",
  "EF",
  "EGTND",
  "EH",
  "ELSY",
  "ELYIMB",
  "EMPHYSEMA",
  "ENTS",
  "ENTERIC FEVER",
  "ENDOMETRIOSIS",
  "ENCEPHALOPATHY",
  "ENTC",
  "ENTERITIS",
  "EOS",
  "EPISCLERITIS",
  "EPIGASTRIC",
  "EPI",
  "EPTXS",
  "EPTB",
  "EPS",
  "EP",
  "EPISTAXIS",
  "EPCTYD",
  "EPGLVS",
  "EPISODIC GHABRAHAT",
  "EROSIONS",
  "ERYDMA",
  "ESS",
  "ESS TREMORS",
  "ESRD",
  "ESP",
  "ESPTS",
  "ESPLCDS",
  "ETHMOIDITIS",
  "EUTHYROID",
  "EXERTIONAL ANGINA",
  "EZDRTS",
  "FAMILIAL ADENOMATOUS POLYPOSIS",
  "FATIGUE",
  "FB",
  "FBD",
  "FBMTS",
  "FBDU",
  "FBRADS",
  "FCPD",
  "FC",
  "FDE",
  "FEVER UNDER EVALUATION",
  "FEET NUMBNESS",
  "FEVER",
  "FEET AT RISK",
  "FFM",
  "FGTFNS",
  "FHO",
  "FILIFORM WARTS",
  "FILIFORM WART",
  "FIBROIDS",
  "FIBROSIS",
  "FIBROADENOMA",
  "FILARIASIS",
  "FLE",
  "FL",
  "FLU",
  "FLTSSLP",
  "FLD",
  "FLATULENCE",
  "FLANA",
  "FMYGA",
  "FNLDSR",
  "FOOT CORN",
  "FOOD POISONING",
  "FOLLICULITIS",
  "FPHL",
  "FQBWMT",
  "FRCLS",
  "FRICTIONAL AMYLOIDOSIS",
  "FRLMA",
  "FROZEN SHOULDER",
  "FRNS",
  "FSE",
  "FSGS",
  "FTT",
  "FUNGAL SKIN INFECTION",
  "FUO",
  "FUC",
  "GAD",
  "GASTROPATHY",
  "GANGLION",
  "GALACTORRHOEA",
  "GALL STONE",
  "GANGRENE",
  "GAO",
  "GATCS",
  "GASTROCOLITIS",
  "GBSPHYS",
  "GBCL",
  "GBDPYP",
  "GBSGE",
  "GBPOLYPS",
  "GBS",
  "GDM",
  "GERD",
  "GENERALISED WEAKNESS",
  "GHD",
  "GI BLEED",
  "GI UPSET",
  "GIARDIASIS",
  "GI INFECTION",
  "GI SEPSIS",
  "GIDDINESS",
  "GLTXY",
  "GLUCOMA",
  "GLUTEAL ABSCESS",
  "GLTRA",
  "GLAUCOMA",
  "GLOSSITIS",
  "GLCPLS",
  "GME",
  "GNGTS",
  "GNDPRTS",
  "GOITRE",
  "GOUTY ARTHRITIS",
  "GOUT",
  "GOPTY",
  "GPN",
  "GPRAS",
  "GRANULATION IN EAR CANAL",
  "GR1B",
  "GRD",
  "GSETS",
  "GS",
  "GSD",
  "GSAD",
  "GSS",
  "GT",
  "GTTCS",
  "GTR",
  "GTCS",
  "GYN",
  "HAND ECZEMA",
  "HAIRFALL",
  "HARD WAX",
  "HAND TREMORS",
  "HAEMOPTYSIS",
  "HANSD",
  "HAEMATURIA",
  "HAEMATOMA",
  "HBP",
  "HBS HCV HIV NEGATIVE",
  "HBV",
  "HCR",
  "HCVRK",
  "HCM",
  "HCC",
  "HCYT",
  "HCV",
  "HDA",
  "HDLA",
  "HDMIM",
  "HD",
  "HEMOPTYSIS",
  "HEAT STROKE",
  "HERPES SIMPLEX",
  "HEAD INJURY",
  "HEP A",
  "HEP E",
  "HEMATOCHEZIA",
  "HEADACHE",
  "HEMORRHOIDS",
  "HEEL PAIN",
  "HEAVINESS",
  "HEPATOSPLENOMEGALY",
  "HEMATEMESIS",
  "HEPTS",
  "HEP B",
  "HEP C",
  "HEPATOMEGALY",
  "HFPEF",
  "HFREF",
  "HFM",
  "HFNEF",
  "HF",
  "HGC",
  "HHD",
  "HIDRADENITIS SUPPURATIVA",
  "HICCUPS",
  "HIV NEGATIVE",
  "HLP",
  "HLF",
  "HMPS",
  "HMRDS",
  "HMTR",
  "HMTS",
  "HM",
  "HOCM",
  "HOT FLASHES",
  "HOARSE VOICE",
  "HPSLS",
  "HPT",
  "HPSPGS",
  "HPE",
  "HPTCECPY",
  "HPHRKT",
  "HRNA",
  "HRLS",
  "HRNLS",
  "HSP",
  "HTN",
  "HTG",
  "HTX",
  "HTM",
  "HTSM",
  "HTVNPS",
  "HUNGRY",
  "HVS",
  "HYPERTENSION",
  "HYPTM",
  "HYGM",
  "HYALA",
  "HYDNPS",
  "HYPAD",
  "HYPER-BILIRUBINEMIA",
  "HYPERTRICHOSIS",
  "HYPOKPP",
  "HYSTERECTOMY",
  "HYUMA",
  "HYPLA",
  "HYVMA",
  "HYVT",
  "HYPINSL",
  "HYPOCHONDRIAC",
  "HYPOGONADISM",
  "HYPERMENORRHEA",
  "HYTGMA",
  "HYMA",
  "HYGDM",
  "HYPT",
  "HYHCMA",
  "HYADA",
  "HYPO PIGMENTED PATCHES",
  "HYCLMA",
  "HYCH",
  "HYKA",
  "HYPDM",
  "HYPERHOMOCYSTEINEMIA",
  "HYPERPIGMENTATION",
  "HYPOPIGMENTATION",
  "HYHYGM",
  "HYTM",
  "HYPLDA",
  "HYPERKALEMIA",
  "HYPA",
  "HYRCLMA",
  "HYDROCELE",
  "HYPERTENSIVE RETINOPATHY",
  "HYPLPS",
  "HYPERSPLENISM",
  "HYPONATRAEMIA",
  "HYPEROPIA",
  "HZ",
  "IBS",
  "IBD",
  "IBR",
  "IBW",
  "ICH",
  "IC BLEED",
  "ICS",
  "ICCD",
  "ICHTHYOSIS",
  "ICMP",
  "ICD",
  "ICAD",
  "ICTERUS",
  "IDA",
  "IDCM",
  "IED",
  "IFG",
  "IGE",
  "IGT",
  "IGH",
  "IGAN",
  "IHD",
  "IHH",
  "ILD",
  "ILI",
  "IMSC",
  "IMPACTED WAX",
  "IMPETIGO",
  "IMGCA",
  "INTERMITTENT BREATHLESSNESS UNDER EVALUATION",
  "INSECT BITE",
  "INJURY",
  "INFECTED LEFT FOOT WOUND",
  "INFERTILITY",
  "INTERTRIGO",
  "INSAMBS",
  "INDIGESTION",
  "INFECTED SEBACEOUS CYST",
  "INGROWN TOENAIL",
  "INFECTED RIGHT LEG WOUND",
  "INFECTED MASTOID CAVITY",
  "INSOMNIA",
  "INMNA",
  "INS",
  "INCLC",
  "INSECTICIDE POISONING",
  "INFECTION",
  "IOOA",
  "IPF",
  "IPD",
  "IRRITABLE BOWEL SYNDROME",
  "IRON DEFICIENCY ANAEMIA",
  "IRD",
  "IRRITABILITY",
  "IRREGULAR PERIODS",
  "IRS",
  "IRREGULAR MENSES",
  "ISCHEMIA",
  "ISH",
  "ISS",
  "ISHLN",
  "ISR",
  "ITP",
  "ITCHING",
  "IVDP",
  "IWMI",
  "IWSTEMI",
  "JOINT PAIN",
  "JTPN",
  "JUD",
  "KERATOTIC WAX",
  "KETOSIS",
  "KELOIDAL SCAR",
  "KERATOSIS OBTURANS",
  "KHD",
  "KNEE PAIN",
  "KNEPN",
  "KP",
  "KRSPS",
  "KS",
  "KUB CALCULI",
  "KYPHOSCOLIOSIS",
  "KYPHOSIS",
  "LACI",
  "LAHB",
  "LAD",
  "LACK OF ENERGY",
  "LADA",
  "LADCTS",
  "LBBB",
  "LBP",
  "LBR",
  "LBA",
  "LBPN",
  "LCS",
  "LCRPS",
  "LCTSI",
  "LCX",
  "LCNPLS",
  "LCHEPN",
  "LDIABETIC FOOT",
  "LD",
  "LDNS",
  "LEUKOPENIA",
  "LEFT LEG INJURY",
  "LEFT EYEBROW INJURY",
  "LEFT LUMBAR PAIN",
  "LEFT KNEE PAIN",
  "LETHARGY",
  "LEFT CHARCOT FOOT SYNDROME",
  "LE",
  "LEFT FLANK PAIN",
  "LEUCORRHEA",
  "LEFT ARM PAIN",
  "LEFT BASAL PNEUMONIA",
  "LEUKOPLAKIA",
  "LEFT SMALL KIDNEY",
  "LEUKOCYTOSIS",
  "LEFT SHOULDER PAIN",
  "LEUCORRHOEA",
  "LEFT FOOT WOUND",
  "LEFT FOOT INJURY",
  "LEG PAIN",
  "LEFT SIDE HYDRONEPHROSIS",
  "LESIONS",
  "LEFT HAND INJURY",
  "LESION",
  "LFDE",
  "LGQTSYM",
  "LHR",
  "LHMPS",
  "LIPOMA",
  "LICHNFN",
  "LIQUID DIET",
  "LITTLE'S AREA BLEEDING",
  "LIC",
  "LIMA",
  "LICHEN NITIDUS",
  "LIVER ENZYME RAISED",
  "LIPOMASTIA",
  "LKNEPN",
  "LLPN",
  "LMRSPS",
  "LMRR",
  "LMCAI",
  "LNGCA",
  "LN",
  "LOOSE MOTION",
  "LOSS OF APPETITE",
  "LOW BODY WEIGHT",
  "LPCTS",
  "LPDTS",
  "LPP",
  "LPR",
  "LPSNPS",
  "LRECL",
  "LRSK",
  "LRA",
  "LRI",
  "LRTI",
  "LRP",
  "LSS",
  "LSMTN",
  "LSC",
  "LSPTS",
  "LSOLBD",
  "LT BC AVF",
  "LTSHPN",
  "LTECFE",
  "LTPSPKA",
  "LTEM",
  "LTULRPN",
  "LTAMNBS",
  "LT RC AVF",
  "LTETRPN",
  "LTVSBTY",
  "LUTS",
  "LUBP",
  "LUMBAGO",
  "LVDFN",
  "LVD",
  "LVFLR",
  "LVF",
  "LVDD",
  "LVCRS",
  "LVABS",
  "LVT",
  "LVH",
  "LVEF",
  "LVSD",
  "LWBP",
  "LYS",
  "LYPTY",
  "LYDTS",
  "LYTCFS",
  "MADD",
  "MALARIA ANTIGEN NEG",
  "MALENA",
  "MASTALGIA",
  "MAU",
  "MAAU",
  "MAPA",
  "MACULOPATHY",
  "MALAISE",
  "MATSM",
  "MACROCYTOSIS",
  "MAYDS",
  "MBHD",
  "MCD",
  "MCPLA",
  "MCTD",
  "MCA",
  "MCAS",
  "MDTGTE",
  "MDD",
  "MDP",
  "MDS",
  "MELENA",
  "MENINGIOMA",
  "METABOLIC ACIDOSIS",
  "MEIBOMIANITIS",
  "MENORRHAGIA",
  "METABOLIC ENCEPHALOPATHY",
  "METFORMIN INTOLERANCE",
  "MEMORY LOSS",
  "METFORMIN INDUCED GI DISTURBANCES",
  "MENINGITIS",
  "MELASMA",
  "MENOPAUSE",
  "METFORMIN INTOLERANT",
  "MENISCUS INJURY",
  "MELANOSIS",
  "MFPS",
  "MG",
  "MGLBA",
  "MGN",
  "MHD",
  "MHYA",
  "MICPMA",
  "MIRAS",
  "MICROPHALLUS",
  "MICROADENOMA",
  "MICTURITION",
  "MISCARRIAGE",
  "MILIA",
  "MICT",
  "MJP",
  "MLR",
  "MLRPN",
  "MLTIFT",
  "MLS",
  "MLMCGM",
  "MLNCNV",
  "MLEJPN",
  "MMYMA",
  "MNTLRTN",
  "MN",
  "MNG",
  "MNRDS",
  "MODERATE PH",
  "MODY",
  "MODS",
  "MODERATE AS",
  "MPH",
  "MPGN",
  "MR",
  "MRBKPN",
  "MRD",
  "MRASA",
  "MSCLN",
  "MSP",
  "MSY",
  "MSLCRPS",
  "MTBSYM",
  "MTLVSS",
  "MTNSKS",
  "MUSCULAR PAIN",
  "MULTIPLE PATCHES",
  "MUSCLE SPASM",
  "MUP",
  "MUSCLE SPRAIN",
  "MUSCLE STRAIN",
  "MVR",
  "MVP",
  "MXLCPNA",
  "MYXOEDEMA",
  "MYOCARDIAL ISCHEMIA",
  "MYGA",
  "MYCI",
  "MYOSITIS",
  "MYOPIA",
  "MYRINGITIS",
  "MYCLBGE",
  "NAUSEA",
  "NASH",
  "NANMA",
  "NASAL POLYPS",
  "NAFLD",
  "NBA",
  "NC",
  "NCCYS",
  "NCCP",
  "NCNLES",
  "NDCY",
  "NEURALGIA",
  "NECK PAIN",
  "NEURALGIC IRRITABILITY",
  "NEPHROLITHIASIS",
  "NEURITIS",
  "NECK SPRAIN",
  "NEPTY",
  "NEPH",
  "NEUTROPHILIA",
  "NEURASTHENIA",
  "NF",
  "NLV",
  "NON HEALING PERFORATION",
  "NORMAL DIET",
  "NODAT",
  "NOSE FRACTURE",
  "NORMOGLYCAEMIA",
  "NOCTURIA",
  "NPDR",
  "NPHRPRA",
  "NPH",
  "NRPTY",
  "NRS",
  "NSAID ABUSE",
  "NSR",
  "NSTEMI",
  "NSCLTS",
  "NS",
  "NUMBNESS",
  "NUD",
  "OA",
  "OAD",
  "OAB",
  "OATGLA",
  "OAK",
  "OBTY",
  "OBTY GRADE 3",
  "OBJCE",
  "OBUPY",
  "OCD",
  "ODA",
  "OE",
  "OEDEMA",
  "OESOPHAGITIS",
  "OGPSNG",
  "OHA",
  "OLIGOMENORRHEA UNDER EVALUATION, SINUSITIS",
  "OLLNPS",
  "OLS",
  "OLSMA",
  "OLIGOMENORRHEA",
  "OME",
  "ONT",
  "ONCMS",
  "OPHIASIS",
  "OPP",
  "ORLMTS",
  "ORCHITIS",
  "ORLCDS",
  "ORGANOPHOSPHORUS POISONING",
  "OSTPS",
  "OSTEOPENIA",
  "OSAHS",
  "OSA",
  "OSTMA",
  "OSTIAL PLAQUE",
  "OSMF",
  "OSAS",
  "OSD",
  "OTC",
  "OTALGIA",
  "OTCLRS",
  "OTITIS",
  "OTITIS MEDIA",
  "OTOSCLEROSIS",
  "OUP",
  "OVCY",
  "OVERWEIGHT",
  "PARKD",
  "PAR",
  "PANLABS",
  "PALMAR WART",
  "PASCYI",
  "PANIC",
  "PARAPARESIS",
  "PANCREATIC DIABETES",
  "PARTIAL EMPTY SELLA",
  "PAPULAR SCARS",
  "PAMI",
  "PACHYGYRIA",
  "PANGASTRITIS",
  "PAINFUL MICTURITION",
  "PAIN",
  "PAH",
  "PARTS",
  "PALPITATIONS",
  "PAF",
  "PARONYCHIA",
  "PARESTHESIA",
  "PARAPHIMOSIS",
  "PATD",
  "PASNGN",
  "PALLOR",
  "PALPITATION",
  "PBS",
  "PCOS",
  "PCTLPLS",
  "PCNA",
  "PCI",
  "PCST",
  "PCOD",
  "PCRT",
  "PCLEFN",
  "PDA",
  "PDRMTS",
  "PDR",
  "PD",
  "PDE",
  "PERENIAL ALLERGIC RHINITIS",
  "PERIUNGUAL WARTS",
  "PERIORAL MELANOSIS",
  "PE",
  "PERIARTHERITIS",
  "PEDAL EDEMA",
  "PED",
  "PEID",
  "PEMPHIGUS VULGARIS",
  "PERITONSILLITIS",
  "PECTS",
  "PGDM",
  "PHMS",
  "PHYPDM",
  "PH",
  "PHOTOPIGMENTATION",
  "PHARYNGOTONSILLITIS",
  "PHNGA",
  "PHDS",
  "PHGTS",
  "PHN",
  "PIGMENTATION",
  "PIVD",
  "PITUITARY ADENOMA",
  "PID",
  "PILES",
  "PIITP",
  "PIH",
  "PICA",
  "PKD",
  "PLTEM",
  "PLE",
  "PLEURITIS",
  "PLF",
  "PLYMHA",
  "PLWHA",
  "PLPSS",
  "PLC",
  "PLDMRM",
  "PLCY",
  "PLANTAR WARTS",
  "PMS",
  "PMLE",
  "PMNS",
  "PMHS",
  "PMO",
  "PME",
  "PMPYX",
  "PMC",
  "PNS",
  "PNHYTM",
  "PN",
  "PNEUMONIA",
  "PNC",
  "PNDSR",
  "PNEUMONITIS",
  "PND",
  "PNEUMOTHORAX",
  "PNCL",
  "POST INFECTIOUS COUGH",
  "POI",
  "POHYLS",
  "POLYURIA",
  "POST DVR",
  "POSTMENOPAUSAL",
  "POM",
  "POST TSS",
  "POST VIRAL RESPIRATORY SEQUELAE",
  "POAG",
  "POST PTCA",
  "POMPHOLYX",
  "POST IWMI",
  "POST VIRAL ARTHRITIS",
  "PODRTS",
  "POOR GLYCEMIC CONTRO",
  "POLYPHAGIA",
  "PPT",
  "PPP",
  "PPHG",
  "PPI",
  "PPM",
  "PPCD",
  "PPV",
  "PPK",
  "PPH",
  "PPPD",
  "PRXA",
  "PRM",
  "PROCTITIS",
  "PRP",
  "PRIMARY SUBFERTILITY",
  "PRIMARY INFERTILITY",
  "PRAD",
  "PROSTATOMEGALY",
  "PROSTATISM",
  "PRL",
  "PRXIA",
  "PRDTS",
  "PRURITUS",
  "PRT",
  "PRTS",
  "PRIMARY AMENORRHEA",
  "PRIS",
  "PREGNANCY",
  "PRAS",
  "PROTEINURIA",
  "PRLMA",
  "PREPUBERTAL",
  "PRATHS",
  "PROFUSE SWEATING",
  "PSBPA",
  "PSN",
  "PSYD",
  "PSYDSR",
  "PSPKA",
  "PSVT",
  "PSYCHOSIS",
  "PSVCR",
  "PSS",
  "PTYMAMA",
  "PTHYDA",
  "PTE",
  "PTLVTS",
  "PTGSX",
  "PTCA",
  "PTB",
  "PTCNA",
  "PTRSA",
  "PTC",
  "PTERYGIUM",
  "PTF",
  "PTA",
  "PTNSDFY",
  "PT",
  "PTM",
  "PTSD",
  "PUS",
  "PUFFY FACE",
  "PULR",
  "PUO",
  "PUVASOL",
  "PUSTULE",
  "PUI",
  "PUFI",
  "PUD",
  "PUSTULES",
  "PVS",
  "PV",
  "PVD",
  "PVOD",
  "PVR",
  "PYTS",
  "PYOSPERMIA",
  "PYMFS",
  "PYGCMGS",
  "PYAGA",
  "RARTS",
  "RAI",
  "RACTURE",
  "RAD",
  "RADCTS",
  "RAYDS",
  "RADPTY",
  "RASHES",
  "RASH",
  "RBBB",
  "RBLDG",
  "RCTCA",
  "RCBLIT",
  "RCA",
  "RCTS",
  "RCRDTY",
  "RDS",
  "RDFU",
  "RDNS",
  "RDLRPN",
  "RESTLESSNESS",
  "RENAL INSUFFICIENCY",
  "RETROVIRUS INFECTION",
  "RESPISY",
  "RENAL CYST",
  "RE",
  "RESTRICTIVE LUNG DISEASE",
  "RECURRENT FOLLICULITIS",
  "REDEYES",
  "RETROVIRAL INFECTION",
  "RECL",
  "RENAL ARTERY STENOSIS",
  "REPAS",
  "RENC",
  "RESPIRATORY FAILURE",
  "RFLE",
  "RF",
  "RFVEER",
  "RHTFVR",
  "RHF",
  "RHMPS",
  "RH",
  "RHTS",
  "RHD",
  "RHONCHI",
  "RHMS",
  "RIGHT FOOT WOUND",
  "RIGOR",
  "RIGHT FOOT INJURY",
  "RIGHT SMALL KIDNEY",
  "RIGHT FLANK PAIN",
  "RIGHT BASAL CONSOLIDATION",
  "RIGHT HAND INJURY",
  "RIGHT HAND INFECTION",
  "RIGHT ARM PAIN",
  "RIGHT LITTLE'S AREA BLEEDING",
  "RIGHT SHOULDER PAIN",
  "RICKETS",
  "RIGHT LUNG  PNEUMONIA",
  "RKNEPN",
  "RLYDTS",
  "RLLP",
  "RLS",
  "RMCAI",
  "ROLLING SCARS",
  "ROVCY",
  "ROS",
  "RPCTS",
  "RPGN",
  "RPY",
  "RP",
  "RPD",
  "RPCTN",
  "RPRF",
  "RRLCYT",
  "RSVG",
  "RS",
  "RSPTS",
  "RSD",
  "RTPCR POSITIVE",
  "RTPSPKA",
  "RTEBLD",
  "RTTCIT",
  "RTTHYAA",
  "RTA4",
  "RTI",
  "RTA",
  "RTTWND",
  "RTSHPN",
  "RTHYDNPS",
  "RTSLBRN",
  "RTHCPN",
  "RTCHCS",
  "RUNNY NOSE",
  "RVUJCLS",
  "RVHD",
  "RVF",
  "RVD",
  "RVDYFN",
  "SARTORIUS PAIN",
  "SAOM",
  "SAT",
  "SAGH",
  "SAH",
  "SAR",
  "SATHYTS",
  "SAIO",
  "SBMCSFS",
  "SBRCMS",
  "SBSCYT",
  "SCH",
  "SCTT",
  "SCABIES",
  "SCARS",
  "SCT",
  "SCIATICA",
  "SCZ",
  "SCLERITIS",
  "SCHIZOPHRENIA",
  "SCLERODERMA",
  "SCDS",
  "SDH",
  "SDRMTS",
  "SEZ",
  "SECONDARY INFERTILITY",
  "SEPSIS",
  "SEPTIC SHOCK",
  "SEVERE ITCHING",
  "SECONDARY AMENORRHOEA",
  "SENILE",
  "SECONDARY INFECTION",
  "SECONDARY  AMENORRHEA",
  "SECONDARY AMENORRHEA",
  "SEBACEOUS CYST",
  "SECONDARY OHA FAILURE",
  "SFLU",
  "SHC",
  "SHOCK",
  "SHA",
  "SHORT STATURE",
  "SHYPDM",
  "SHSYM",
  "SHIVERING",
  "SHT",
  "SHLPN",
  "SINGLE KIDNEY",
  "SINGLE PATCH",
  "SINGLE FETUS",
  "SIBO",
  "SIGNS OF DEHYDRATION",
  "SINUS BRADYCARDIA",
  "SIADH",
  "SINGLE RIGHT KIDNEY",
  "SIALADENITIS",
  "SJSYM",
  "SKIN ALLERGY",
  "SKIN RASHES",
  "SKIN TAGS",
  "SLPANA",
  "SLURRED SPEECH",
  "SLE",
  "SLVD",
  "SLPDPTN",
  "SMALL PHALLUS",
  "SM",
  "SMTFDSR",
  "SMOKING",
  "SMF",
  "SMOKER",
  "SMA",
  "SMOKERS LUNGS",
  "SNEEZING",
  "SNRPTY",
  "SNHL",
  "SNSLPS",
  "SNORING",
  "SND",
  "SNSTS",
  "SNPDR",
  "SOULDER JOINT TENDINOSIS",
  "SORE THROAT",
  "SOB",
  "SOM",
  "SOFT CORN",
  "SOMATIZATION",
  "SPRAS",
  "SPRAIN",
  "SPD",
  "SPONDYLARTHRITIS",
  "SPRATS",
  "SPTA",
  "SPA",
  "SPLENOMEGALY",
  "SPONDYLOSIS",
  "SRATS",
  "SRBTYS",
  "SRDS",
  "SRDRTS",
  "SS",
  "SSS",
  "STABLE ANGINA",
  "STHPS",
  "STRDSE",
  "STI",
  "STIFFNESS",
  "STN",
  "STCUTA",
  "STRESS DISORDER",
  "STMT",
  "STOMACH HEAVINESS",
  "STASIS ECZEMA",
  "STARING",
  "STEROID DEPENDECY",
  "STEMI",
  "STE",
  "STRIAE",
  "STRESS",
  "SUFFOCATING SENSATION",
  "SUICIDAL TENDENCY",
  "SUBFERTILITY",
  "SUBNEPHROTIC PROTEINURIA",
  "SUBACUTE NM RIGHT EARACHE",
  "SVT",
  "SVG-D1",
  "SVD",
  "SWOLLEN FEET",
  "SWTG",
  "SWELLING",
  "SYRINGOMAS",
  "SYSLS",
  "SYNCOPE",
  "SYNCOPAL ATTACK",
  "SYCATK",
  "SYNDROMIC",
  "SZRDSR",
  "TAO",
  "TACHYCARDIA",
  "TANDEM PLAQUE",
  "TB",
  "TBLYADTS",
  "TBM",
  "TCPA",
  "TCP",
  "TCS",
  "TDS",
  "TENSION HEADACHE",
  "TENDENOSIS",
  "TETANY",
  "TENDINITIS",
  "TGD",
  "THR",
  "THROMBOLYSIS",
  "THYN",
  "THTIN",
  "THROAT DRYNESS",
  "THBCYTS",
  "THROAT PAIN",
  "THYDS",
  "THYCA",
  "THORAT INFECTION",
  "THYMOMA",
  "TIACTS",
  "TIA",
  "TINEA INFECTION",
  "TICS",
  "TIREDNESS",
  "TKR",
  "TLSMA",
  "TLE",
  "TLPEPSY",
  "TMJD",
  "TMGLY",
  "TMJ",
  "TMNG",
  "TNLTS",
  "TNLRD",
  "TNC",
  "TNEFLM",
  "TNA",
  "TNT",
  "TNLPTS",
  "TOOTHACHE",
  "TOXICOSIS",
  "TOBACCO CHEWER",
  "TPO NEGATIVE",
  "TPE",
  "TPO - VE",
  "TPO POSITIVE",
  "TRTLS",
  "TRAUMATIC PERFORATION",
  "TRBPTS",
  "TRANSAMINITIS",
  "TRIGGER FINGER",
  "TRDRN",
  "TRNALA",
  "TREMORS",
  "TR",
  "TRUE",
  "TRS",
  "TSLRHY",
  "TS",
  "TSH",
  "TSELW",
  "TTH",
  "TUGM",
  "TUBS",
  "TURP",
  "TUL",
  "TVD",
  "TVCLR",
  "TWBFIN",
  "TWIN PREGNANCY",
  "TYPHOID FEVER",
  "TYPE 1 RESPIRATORY FAILURE",
  "TYTXS",
  "TYPE 2 RESPIRATORY FAILURE",
  "UAD",
  "UBP",
  "UC",
  "UCTD",
  "UCDGYMA",
  "UCS",
  "ULCER",
  "ULC",
  "UNDERWEIGHT",
  "UNWELL",
  "UNSTABLE ANGINA",
  "UNEASINESS",
  "URTI",
  "URI",
  "URETERIC COLIC",
  "URYICE",
  "URYRTN",
  "URPS",
  "URTLS",
  "URT",
  "URETHRAL STRICTURE",
  "UTCL",
  "UTNPLS",
  "UTCRA",
  "UTI",
  "UVEITIS",
  "VARICOSE ECZEMA",
  "VASCULITIS",
  "VAGINAL CANDIDIASIS",
  "VBI",
  "VDD",
  "VERRUCA VULGARIS",
  "VERTIGO",
  "VERRUCA PLANA",
  "VFEVER",
  "VF",
  "VGNTS",
  "VHA",
  "VHD",
  "VHDA",
  "VHF",
  "VIRAL PNEUMONIA",
  "VIRAL INFECTION",
  "VIRAL EXANTHEM",
  "VIRAL  INFECTION",
  "VIRAL",
  "VITILIGO VULGARIS",
  "VIRAL COLD",
  "VIRAL RASHES",
  "VKC",
  "VLVVGTS",
  "VLEXM",
  "VMR",
  "VNSSTS",
  "VNSISFY",
  "VOMITING",
  "VOMITIG",
  "VPD",
  "VPC",
  "VRT",
  "VRSVN",
  "VRCZ",
  "VRDTA",
  "VSVLSYC",
  "VSD",
  "VST",
  "VTDD",
  "VTB12D",
  "VTLGO",
  "VTD3D",
  "VVLLS",
  "WAX",
  "WARTS",
  "WASP BITE",
  "WEAKNESS",
  "WGR3ULR",
  "WHEEZE",
  "WHEEZING",
  "WOUND",
  "WPWS",
  "WTGN",
  "WTLS",
  "XANTHELASMA",
  "XEROSIS",
  "XERODERMA",
  "XTMAPM",
  "Abdominal aortic aneurysm",
  "Acne",
  "Acute cholecystitis",
  "Acute lymphoblastic leukaemia",
  "Acute lymphoblastic leukaemia: Children",
  "Acute lymphoblastic leukaemia: Teenagers and young adults",
  "Acute myeloid leukaemia",
  "Acute myeloid leukaemia: Children",
  "Acute myeloid leukaemia: Teenagers and young adults",
  "Acute pancreatitis",
  "Addison's disease",
  "Alcohol-related liver disease",
  "Allergic rhinitis",
  "Allergies",
  "Alzheimer's disease",
  "Anal cancer",
  "Anaphylaxis",
  "Angioedema",
  "Ankylosing spondylitis",
  "Anorexia nervosa",
  "Anxiety",
  "Anxiety disorders in children",
  "Appendicitis",
  "Arthritis",
  "Asbestosis",
  "Asthma",
  "Atopic eczema",
  "Attention deficit hyperactivity disorder (ADHD)",
  "Autistic spectrum disorder (ASD)",
  "Bacterial vaginosis",
  "Benign prostate enlargement",
  "Bile duct cancer (cholangiocarcinoma)",
  "Binge eating",
  "Bipolar disorder",
  "Bladder cancer",
  "Blood poisoning (sepsis)",
  "Bone cancer",
  "Bone cancer: Teenagers and young adults",
  "Bowel cancer",
  "Bowel incontinence",
  "Bowel polyps",
  "Brain stem death",
  "Brain tumours",
  "Brain tumours: Children",
  "Brain tumours: Teenagers and young adults",
  "Breast cancer (female)",
  "Breast cancer (male)",
  "Bronchiectasis",
  "Bronchitis",
  "Bulimia",
  "Carcinoid syndrome and carcinoid tumours",
  "Catarrh",
  "Cellulitis",
  "Cerebral palsy",
  "Cervical cancer",
  "Chest infection",
  "Chest pain",
  "Chickenpox",
  "Chilblains",
  "Chlamydia",
  "Chronic fatigue syndrome",
  "Chronic kidney disease",
  "Chronic lymphocytic leukaemia",
  "Chronic myeloid leukaemia",
  "Chronic obstructive pulmonary disease",
  "Chronic pain",
  "Chronic pancreatitis",
  "Cirrhosis",
  "Clostridium difficile",
  "Coeliac disease",
  "Cold sore",
  "Coma",
  "Common cold",
  "Common heart conditions",
  "Congenital heart disease",
  "Conjunctivitis",
  "Constipation",
  "Coronavirus (COVID-19)",
  "Cough",
  "Crohn's disease",
  "Croup",
  "Cystic fibrosis",
  "Cystitis",
  "Deafblindness",
  "Deep vein thrombosis",
  "Dehydration",
  "Dementia",
  "Dementia with Lewy bodies",
  "Dental abscess",
  "Depression",
  "Dermatitis herpetiformis",
  "Diabetes",
  "Diarrhoea",
  "Discoid eczema",
  "Diverticular disease and diverticulitis",
  "Dizziness (Lightheadedness)",
  "Down's syndrome",
  "Dry mouth",
  "Dysphagia (swallowing problems)",
  "Dystonia",
  "Earache",
  "Earwax build-up",
  "Ebola virus disease",
  "Ectopic pregnancy",
  "Edwards' syndrome",
  "Endometriosis",
  "Epilepsy",
  "Erectile dysfunction (impotence)",
  "Escherichia coli (E. coli) O157",
  "Ewing sarcoma",
  "Ewing sarcoma: Children",
  "Eye cancer",
  "Febrile seizures",
  "Feeling of something in your throat (Globus)",
  "Fever in adults",
  "Fever in children",
  "Fibroids",
  "Fibromyalgia",
  "Farting",
  "Flu",
  "Foetal alcohol syndrome",
  "Food poisoning",
  "Functional neurological disorder (FND)",
  "Fungal nail infection",
  "Gallbladder cancer",
  "Gallstones",
  "Ganglion cyst",
  "Gastroenteritis",
  "Gastro-oesophageal reflux disease (GORD)",
  "Genital herpes",
  "Genital symptoms",
  "Genital warts",
  "Germ cell tumours",
  "Glandular fever",
  "Gonorrhoea",
  "Gout",
  "Gum disease",
  "Haemorrhoids (piles)",
  "Hand, foot and mouth disease",
  "Hay fever",
  "Head and neck cancer",
  "Head lice and nits",
  "Headaches",
  "Hearing loss",
  "Heart failure",
  "Hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Hiatus hernia",
  "High cholesterol",
  "HIV",
  "Hodgkin lymphoma",
  "Hodgkin lymphoma: Children",
  "Hodgkin lymphoma: Teenagers and young adults",
  "Huntington's disease",
  "Hyperglycaemia (high blood sugar)",
  "Hyperhidrosis",
  "Hypoglycaemia (low blood sugar)",
  "Idiopathic pulmonary fibrosis",
  "Impetigo",
  "Indigestion",
  "Ingrown toenail",
  "Inherited heart conditions",
  "Insomnia",
  "Iron deficiency anaemia",
  "Irritable bowel syndrome (IBS)",
  "Irritable hip",
  "Itching",
  "Itchy bottom",
  "Kaposi's sarcoma",
  "Kidney cancer",
  "Kidney infection",
  "Kidney stones",
  "Labyrinthitis",
  "Lactose intolerance",
  "Laryngeal (larynx) cancer",
  "Laryngitis",
  "Leg cramps",
  "Lichen planus",
  "Liver cancer",
  "Liver disease",
  "Liver tumours",
  "Loss of libido",
  "Lung cancer",
  "Lupus",
  "Lyme disease",
  "Lymphoedema",
  "Lymphogranuloma venereum (LGV)",
  "Malaria",
  "Malignant brain tumour (cancerous)",
  "Malnutrition",
  "Measles",
  "Meningitis",
  "Menopause",
  "Mesothelioma",
  "Middle ear infection (otitis media)",
  "Migraine",
  "Miscarriage",
  "Motor neurone disease (MND)",
  "Mouth cancer",
  "Mouth ulcer",
  "Multiple myeloma",
  "Multiple sclerosis (MS)",
  "Mumps",
  "Meniere's disease",
  "Myasthenia gravis",
  "Nasal and sinus cancer",
  "Nasopharyngeal cancer",
  "Neuroblastoma: Children",
  "Neuroendocrine tumours",
  "Non-alcoholic fatty liver disease (NAFLD)",
  "Non-Hodgkin lymphoma",
  "Non-Hodgkin lymphoma: Children",
  "Norovirus",
  "Nosebleed",
  "Obesity",
  "Obsessive-compulsive disorder (OCD)",
  "Obstructive sleep apnoea",
  "Oesophageal cancer",
  "Oral thrush in adults",
  "Osteoporosis",
  "Osteosarcoma",
  "Otitis externa",
  "Ovarian cancer",
  "Ovarian cancer: Teenagers and young adults",
  "Ovarian cyst",
  "Overactive thyroid",
  "Paget's disease of the nipple",
  "Pancreatic cancer",
  "Panic disorder",
  "Parkinson's disease",
  "Patau's syndrome",
  "Pelvic inflammatory disease",
  "Pelvic organ prolapse",
  "Penile cancer",
  "Peripheral neuropathy",
  "Personality disorder",
  "Pleurisy",
  "Pneumonia",
  "Polymyalgia rheumatica",
  "Post-polio syndrome",
  "Post-traumatic stress disorder (PTSD)",
  "Postnatal depression",
  "Pregnancy and baby",
  "Pressure ulcers",
  "Prostate cancer",
  "Psoriasis",
  "Psoriatic arthritis",
  "Psychosis",
  "Pubic lice",
  "Rare tumours",
  "Raynaud's phenomenon",
  "Reactive arthritis",
  "Restless legs syndrome",
  "Retinoblastoma: Children",
  "Rhabdomyosarcoma",
  "Rheumatoid arthritis",
  "Ringworm and other fungal infections",
  "Rosacea",
  "Scabies",
  "Scarlet fever",
  "Schizophrenia",
  "Scoliosis",
  "Septic shock",
  "Shingles",
  "Shortness of breath",
  "Sickle cell disease",
  "Sinusitis",
  "Sjogren's syndrome",
  "Skin cancer (melanoma)",
  "Skin cancer (non-melanoma)",
  "Slapped cheek syndrome",
  "Soft tissue sarcomas",
  "Soft tissue sarcomas: Teenagers and young adults",
  "Sore throat",
  "Spleen problems and spleen removal",
  "Stillbirth",
  "Stomach ache and abdominal pain",
  "Stomach cancer",
  "Stomach ulcer",
  "Streptococcus A (strep A)",
  "Stress, anxiety, and low mood",
  "Stroke",
  "Sudden infant death syndrome (SIDS)",
  "Suicide",
  "Sunburn",
  "Swollen glands",
  "Syphilis",
  "Testicular cancer",
  "Testicular cancer: Teenagers and young adults",
  "Testicular lumps and swellings",
  "Thirst",
  "Threadworms",
  "Thrush",
  "Thyroid cancer",
  "Thyroid cancer: Teenagers and young adults",
  "Tinnitus",
  "Tonsillitis",
  "Tooth decay",
  "Toothache",
  "Transient ischaemic attack (TIA)",
  "Trigeminal neuralgia",
  "Tuberculosis (TB)",
  "Type 1 diabetes",
  "Type 2 diabetes",
  "Trichomonas infection",
  "Transverse myelitis",
  "Ulcerative colitis",
  "Underactive thyroid",
  "Urinary incontinence",
  "Urinary tract infection (UTI)",
  "Urinary tract infection (UTI) in children",
  "Urticaria (hives)",
  "Vaginal cancer",
  "Vaginal discharge",
  "Varicose eczema",
  "Venous leg ulcer",
  "Vertigo",
  "Vitamin B12 or folate deficiency anaemia",
  "Vomiting in adults",
  "Vulval cancer",
  "Warts and verrucas",
  "Whooping cough",
  "Wilms’ tumour",
  "Womb (uterus) cancer",
  "Yellow fever"
]